name: Python_library

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

# on:
#   release:
#     types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Install twine
      run: pip install setuptools twine
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
